version: 2.1
jobs:
  buildandtest_linux_latest:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - run: sudo apt install python3.8-venv
      - checkout
      - run: make test-pkg
  buildandtest_win_latest:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium
    steps:
      - checkout
      - run: python -m pip install pytest flake8
      - run: python -m pip install .
      - run: python -m flake8 -v --max-complexity=20 src tests
      - run: python -m pytest
workflows:
  main:
    jobs:
      - buildandtest_linux_latest
      - buildandtest_win_latest